-- MySQL Script generated by MySQL Workbench
-- Mon Feb 25 23:38:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema leadsDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leadsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leadsDB` DEFAULT CHARACTER SET utf8 ;
USE `leadsDB` ;

-- -----------------------------------------------------
-- Table `leadsDB`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadsDB`.`sales` (
  `sales_ID` INT NULL AUTO_INCREMENT,
  `sales_lname` VARCHAR(45) NULL,
  `sales_fname` VARCHAR(45) NULL,
  `sales_position` VARCHAR(45) NULL,
  `sales_cname` VARCHAR(45) NULL,
  `sales_cnumber` VARCHAR(45) NULL,
  `sales_eadd` VARCHAR(45) NULL,
  `sales_status` VARCHAR(45) NULL,
  `sales_dreg` VARCHAR(45) NULL,
  PRIMARY KEY (`sales_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leadsDB`.`leads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadsDB`.`leads` (
  `leads_ID` INT NULL AUTO_INCREMENT,
  `leads_lname` VARCHAR(45) NULL,
  `leads_fname` VARCHAR(45) NULL,
  `leads_position` VARCHAR(45) NULL,
  `leads_hname` VARCHAR(45) NULL,
  `leads_cnumber` VARCHAR(45) NULL,
  `leads_eadd` VARCHAR(45) NULL,
  `leads_dreg` DATE NULL,
  `sales_sales_ID` INT NOT NULL,
  PRIMARY KEY (`leads_ID`),
  INDEX `fk_leads_sales_idx` (`sales_sales_ID` ASC),
  CONSTRAINT `fk_leads_sales`
    FOREIGN KEY (`sales_sales_ID`)
    REFERENCES `leadsDB`.`sales` (`sales_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
